url: "https://event.mahaputera.art" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Event Seni" # the name of your site, e.g. ACME Corp.

github_username: taufardh
facebook_username: taufardh
linkedin_username: taufardh
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
